src/main/java/ogc/rs/common/DataFromS3.java, src/main/java/ogc/rs/processes/ProcessVerticle.java, src/main/java/ogc/rs/processes/ProcessesRunnerImpl.java
I modified the `compose` method to `onSuccess` in the `DataFromS3` class to handle cases when the request is successful but does not return a 200 status code, ensuring it then transitions to the `onFailure` block.
=> s3-bug-fix

example-config/config-example.json, src/main/java/ogc/rs/apiserver/handlers/DxTokenAuthenticationHandler.java, src/main/java/ogc/rs/apiserver/handlers/User.java
This PR contains following changes:
- Refactoring of authentication
- config changes
=> authentication refactor

src/main/java/ogc/rs/apiserver/ApiServerVerticle.java, src/main/java/ogc/rs/apiserver/handlers/DxTokenAuthenticationHandler.java, src/main/java/ogc/rs/apiserver/handlers/MeteringAuthZHandler.java, src/main/java/ogc/rs/apiserver/handlers/OgcFeaturesAuthZHandler.java, src/main/java/ogc/rs/apiserver/handlers/ProcessAuthZHandler.java, src/main/java/ogc/rs/apiserver/handlers/StacAssetsAuthZHandler.java
- The property skips authN and authZ
=> Bug-Fix: Add 'disable.auth' property check in token authentication and OGC APIs authorization for OGC compliance tests

src/main/java/ogc/rs/processes/ProcessesRunnerImpl.java, src/main/java/ogc/rs/processes/collectionAppending/CollectionAppendingProcess.java, src/main/java/ogc/rs/processes/collectionAppending/Constants.java, src/main/java/ogc/rs/processes/collectionOnboarding/CollectionOnboardingProcess.java
This pull request introduces the **CollectionAppendingProcess** class which handles the process of appending a collection of GeoJSON data (any type of geospatial data format) to an existing collection in a PostgreSQL database. This process includes various steps such as resource ownership checking, collection existence checking, schema validation, data appending to a temporary table, merging the temporary table into the existing collection table, updating bbox values in collection table and deleting temporary table. Below are the key features and steps involved in this implementation:
**Initialization:**
• The CollectionAppendingProcess class is initialized with a PostgreSQL client pool (PgPool), configuration details (including AWS and database information), and a Vertx instance.
• …
=> Collection Appending Process

src/main/java/ogc/rs/apiserver/ApiServerVerticle.java
* Updated the next link for /items Features API.
* Fixed bbox queries returning redundant features.
=> BUG FIX: Fixed next link for Features API

src/main/java/ogc/rs/apiserver/ApiServerVerticle.java, src/main/java/ogc/rs/processes/collectionAppending/CollectionAppendingProcess.java, src/main/java/ogc/rs/processes/collectionOnboarding/CollectionOnboardingProcess.java
This PR contains the refactored code for CRS check in onboarding process in ogrinfo command to extract the authority and code.
=> Code refactor for CRS check in onboarding process

src/main/java/ogc/rs/processes/collectionAppending/CollectionAppendingProcess.java
This pull request includes code refactoring of the append process by reordering the checks for collection existence and resource ownership to ensure successful testing. Additionally, it adds the debug=ON argument to the ogrinfo command line in the append process.
=> Reordering collection existence check and resource ownership check for succeeding the tests.

src/main/java/ogc/rs/apiserver/ApiServerVerticle.java
removed the type array and extra spacing
=> fixes in collection response for type coverage

src/main/java/ogc/rs/apiserver/ApiServerVerticle.java, src/main/java/ogc/rs/apiserver/handlers/ProcessAuthZHandler.java, src/test/java/ogc/rs/restAssuredTest/CollectionAppendingProcessIT.java
**This PR contains:**
-  Provider Delegate Auth Check for processes in ProcessAuthZHandler
- Code refactoring of error handling to use FailureHandler  in ApiServerVerticle
- Tests for provider delegate flow in CollectionAppendingProcessIT
=> Adding provider delegate auth check for processes

src/main/resources/db/migration/V13__tilematrix_metadata_table_refactor.sql
* Fixed data consistency issue
* Old data is now populated in all tables preseving data consistency
=> Update: Tiles Metadata Table Refactor

docs/openapiv3_0.json, docs/openapiv3_0.yaml, src/main/java/ogc/rs/apiserver/ApiServerVerticle.java, src/main/java/ogc/rs/apiserver/router/gisentities/ogccoverages/OgcCoverageEntity.java, src/main/java/ogc/rs/apiserver/util/Constants.java, src/main/java/ogc/rs/database/DatabaseService.java, src/main/java/ogc/rs/database/DatabaseServiceImpl.java, src/test/resources/OGC_Resource_Server_v0.0.3_Release.postman_collection.json
API to fetch the href of collection from database and using that href, the coverageJson is fetched from S3
=> fetching Coverage JSON from S3

src/main/java/ogc/rs/processes/ProcessesRunnerImpl.java
Minor Code Fix in ProcessesRunnerImpl Class
- Added default case in process switch to handle undefined processes
- Resolved the warnings and updated the java docs
=> Minor Code Fix in ProcessesRunnerImpl Class

pom.xml, src/main/java/ogc/rs/deploy/Deployer.java
This commit includes following changes:
1. Integrate Micrometer metrics for Prometheus and bind JVM metrics in deployer.java.
2. Added dependencies for Vert.x Micrometer metrics, Micrometer core, and Prometheus registry in pom
=> Added monitoring metrics

src/main/java/ogc/rs/processes/ProcessesRunnerImpl.java, src/main/java/ogc/rs/processes/s3PreSignedURLGeneration/Constants.java, src/main/java/ogc/rs/processes/s3PreSignedURLGeneration/S3PreSignedURLGenerationProcess.java
Fix: Removed S3 check and added a method to check if the resource is onboarded by querying `collection_type` table based on fileType of the resource.
=> Fix: S3PreSignedURLProcess

docs/stacopenapiv3_0.json, src/main/java/ogc/rs/apiserver/ApiServerVerticle.java, src/main/java/ogc/rs/apiserver/handlers/StacAssetsAuthZHandler.java, src/main/java/ogc/rs/apiserver/router/routerbuilders/StacRouterBuilder.java, src/main/java/ogc/rs/apiserver/util/Constants.java, src/main/java/ogc/rs/database/DatabaseService.java, src/main/java/ogc/rs/database/DatabaseServiceImpl.java, src/main/resources/db/migration/V16__add_stac_items_asset_table.sql
Implementing STAC Items API for Satellite Imagery
=> [DRAFT] STAC Items API

src/main/java/ogc/rs/apiserver/ApiServerVerticle.java, src/main/java/ogc/rs/apiserver/router/routerbuilders/StacRouterBuilder.java, src/main/java/ogc/rs/apiserver/util/Constants.java, src/main/java/ogc/rs/database/DatabaseService.java, src/main/java/ogc/rs/database/DatabaseServiceImpl.java, src/main/java/ogc/rs/database/util/FeatureQueryBuilder.java
* Implemented STAC item-search API
* Modified `FeatureQueryBuilder` to accomodate multiple collections and item-ids in SQL query for search
* Search parameters include; `bbox`, `geometry` intersection, searches across multiple `collections` and `items`
=> [Draft] STAC Item Search API

src/main/java/ogc/rs/apiserver/router/routerbuilders/StacRouterBuilder.java
comment out stac item search route for now because it was failing. Proper fix will be present in STAC Items Search PR
=> Bug-Fix : Comment out the STAC Item Search API route

src/main/java/ogc/rs/apiserver/ApiServerVerticle.java
- Patch fix till we figure out a solution for this
=> Bug-Fix : Increase wait time for router on start-up

src/main/java/ogc/rs/apiserver/ApiServerVerticle.java
Updated the logic to get the collectionId.
=> minor fixes in getStacItem Method 

src/main/java/ogc/rs/processes/s3PreSignedURLGeneration/S3PreSignedURLGenerationProcess.java
- Replaced s3 object key name with RG and RI UUIDs instead of name fields.
=> Replaced s3 object key name with RG and RI UUIDs instead of name fields.

src/main/java/ogc/rs/processes/collectionOnboarding/CollectionOnboardingProcess.java, src/main/java/ogc/rs/processes/collectionOnboarding/Constants.java, src/test/resources/integ-db/teardown/deleteCollectionOnboarding.sql
CollectionOnboardingProcesse updated to insert data into the enclosures table
=> Query Updation for Collection Onboarding Process

src/main/java/ogc/rs/apiserver/router/RouterManager.java
- If postgres connection is lost, the Vert.x LISTEN/NOTIFY channel does not try to auto-connect
- So adding reconnectPolicy to try to reconnect to the channel
- If connection is lost, reconnect will be attempted every **5 seconds for 30 mins**
- If reconnect does not happen in that time, **we stop retrying**
=> Trying to fix connection loss for LISTEN/NOTIFY channel

src/main/java/ogc/rs/processes/s3MultiPartUploadForStacOnboarding/S3InitiateMultiPartUploadProcess.java
This PR modifies the handling of `itemId` and `fileName` from the request input by replacing all special characters except for letters, digits, hyphens `-`, underscores `_`, and dots `.` with underscores `_`.
=> Replace special characters in itemId and fileName with underscores in S3InitiateMultiPartUploadProcess

Jenkinsfile, src/main/java/ogc/rs/apiserver/ApiServerVerticle.java, src/main/java/ogc/rs/apiserver/util/Constants.java, src/main/java/ogc/rs/apiserver/util/StacItemSearchParams.java, src/main/java/ogc/rs/database/DatabaseServiceImpl.java, src/main/java/ogc/rs/database/util/Constants.java, src/main/java/ogc/rs/database/util/FeatureQueryBuilder.java
- Updating Jenkinsfile to add more tests for STAC using `stac-validator`
- Will also try to address any errors/warnings emitted in this PR
=> Updates to STAC Conformance tests

src/main/java/ogc/rs/processes/ProcessesRunnerImpl.java, src/main/java/ogc/rs/processes/featureAttributesExtraction/Constants.java, src/main/java/ogc/rs/processes/featureAttributesExtraction/FeatureAttributesExtractionProcess.java, src/main/resources/db/migration/V27__add_feature_attributes_extraction_process.sql
This PR introduces the `FeatureAttributesExtractionProcess` that extracts specified attributes from all the features in a given collection, excluding geometry. It includes:
-  Validation of collection existence.
-  Attribute validation against the collection schema.
-  Attribute-only feature extraction using dynamic SQL generation.
-  Structured response generation with all the feature IDs and the attributes from the input.
- Progress tracking and job status updates at each step.
**Example Input:**
```
{
"inputs": {
"collectionId": "39b9d0f5-38be-4603-b2db-7b678d9c3870",
"attributes": ["STATE","State_LGD"]
}
}
```
**Example Output:**
```
{
"features": [
{
"id": 1,
"properties": {
"STATE": "ANDAMAN & NICOBAR",
"State_LGD": 35
}
},
{
"id": 2,
"properties": {
"STATE": "ANDHRA PRADESH", …
```
=> Feature Attributes Extraction Process

src/test/java/ogc/rs/restAssuredTest/FeatureAttributesExtractionProcessIT.java
This PR adds integration tests for the FeatureAttributesExtractionProcess.
=> Integration tests for Feature Attributes Extraction Process

docs/openapiv3_0.json, src/main/java/ogc/rs/apiserver/router/gisentities/ogcRecords/OgcRecordsMetadata.java
Minimum offset value changed to 0 from 1
=> Minimum offset value changed to 0
