datakaveri/ogc-resource-server

docs/apidoc.html
src/main/java/ogc/rs/apiserver/router/routerbuilders/EntityRouterBuilder.java

This PR adds functionality to serve an HTML view for the OpenAPI specs when a query parameter f is passed. If f equals html, the server reads an HTML file from the docs folder, replaces the spec-url placeholder with the value from getOasApiPath(), and returns the modified HTML content. If f is not html, the existing flow is followed, returning the JSON OpenAPI specification. This affects endpoints /api, /stac/api, and /metering/api.

oas-html-output

---

src/main/java/ogc/rs/apiserver/router/routerbuilders/EntityRouterBuilder.java

- Get appropriate content type from Accept header if `f` query param is not passed
- `f` query param overrides Accept header if passed

Add handling of Accept header for OpenAPI spec format

---

docker/dev.dockerfile
docker/test.dockerfile

- Without versioning, the latest Ubuntu version is used by default which is causing problems during running of the container
- Encountered libc problems and apt signature problems

Use Focal image of maven-eclipse-temurin

---

docs/dxmeteringopenapiv3_0.json
docs/openapiv3_0.json
docs/stacopenapiv3_0.json
src/main/java/ogc/rs/apiserver/handlers/DxTokenAuthenticationHandler.java
src/main/java/ogc/rs/apiserver/handlers/OgcFeaturesAuthZHandler.java
src/main/java/ogc/rs/apiserver/router/RouterManager.java
src/main/java/ogc/rs/apiserver/router/gisentities/ogcfeatures/CollectionMetadata.java
src/main/java/ogc/rs/apiserver/router/gisentities/ogcfeatures/OgcFeaturesEntity.java
src/main/java/ogc/rs/apiserver/router/gisentities/ogcprocesses/OgcProcessesEntity.java
src/main/java/ogc/rs/apiserver/router/gisentities/ogctiles/OgcTilesEntity.java
src/main/java/ogc/rs/apiserver/router/routerbuilders/DxMeteringRouterBuilder.java
src/main/java/ogc/rs/apiserver/router/routerbuilders/EntityRouterBuilder.java
src/main/java/ogc/rs/apiserver/router/routerbuilders/StacRouterBuilder.java
src/main/java/ogc/rs/apiserver/util/Constants.java
src/main/java/ogc/rs/common/Constants.java
src/test/java/ogc/rs/restAssuredTest/CollectionAppendingProcessIT.java
src/test/java/ogc/rs/restAssuredTest/CollectionOnboardingProcessIT.java
src/test/java/ogc/rs/restAssuredTest/OgcFeaturesIT.java
src/test/java/ogc/rs/restAssuredTest/StacAssetsIT.java
src/test/resources/OGC_Resource_Server_v0.0.3_Release.postman_collection.json

OpenAPI specs
-------------
- Add `securitySchemes` for DX AAA Token and add `security` for non-generated APIs
DxTokenAuthenticationHandler
----------------------------
- Change to `AuthenticationHandler` because normal handler cannot be used in `RouterBuilder.securityHandler()` in `EntityRouterBuilder`
- Handle `Authentication:Bearer <token>` style of header
OgcFeaturesAuthZHandler
-----------------------
- Handle `Authentication:Bearer <token>` style of header
RouterManager
-------------
- Remove handling of `disable.auth` property
- Is now handled in RouterBuilder using `RouterBuilderOptions.setRequireSecurityHandlers()`
CollectionMetadata
------------------
- Remove `token` header param and add `security` key
OgcFeaturesEntity, OgcProcessesEntity, OgcTilesEntity, …

Changed token header from `token` to `Authorization:Bearer ...`

---

src/main/java/ogc/rs/apiserver/router/gisentities/ogccollections/OgcCollectionMetadata.java
src/main/java/ogc/rs/apiserver/router/gisentities/ogccollections/OgcCollectionsEntity.java
src/main/java/ogc/rs/apiserver/router/gisentities/ogccollections/package-info.java
src/main/java/ogc/rs/apiserver/router/gisentities/ogcfeatures/OgcFeaturesMetadata.java
src/main/java/ogc/rs/apiserver/router/routerbuilders/OgcRouterBuilder.java
src/main/java/ogc/rs/database/DatabaseService.java
src/main/java/ogc/rs/database/DatabaseServiceImpl.java

- All OGC APIs (tiles, features, coverages etc.) have the `/collections/<collection-id>` API, so generalising it into a separate spec generation entity - `OgcCollectionsEntity`
- OgcCollectionsEntity also handles spec creation for STAC API `/stac/collections/<collection-id>`
Changes to OGC Features spec generation
---------------------------------------
- Removed generation for `/collections/<collection-id>` API from OgcFeaturesEntity
- Renamed `CollectionMetadata` to `OgcFeaturesMetadata` to make it clear
- Moved GET /collections API to the `OgcRouterBuilder` since it's general for all OGC APIs
- When checking for existing feature collections, checking using `/collections/<UUID>/items` now - since `items` is specific to OGC features

Bug-Fix: Fix spec generation for OGC collections

---

src/main/java/ogc/rs/apiserver/ApiServerVerticle.java
src/main/java/ogc/rs/apiserver/handlers/OgcFeaturesAuthZHandler.java
src/main/java/ogc/rs/apiserver/handlers/StacAssetsAuthZHandler.java
src/main/java/ogc/rs/apiserver/util/AuthInfo.java

- Update AuthInfo object to set the resource ID elsewhere if the token is an open token
- Update STAC and OGC Features AuthZ handlers to remove authInfo JSON object and set the applicable resource ID obtained from DB and endpoint respectively

Fix auditing flows - remove usage of authInfo JSON object in `updateAuditTable` and rely on AuthInfo object

---

docs/dxmeteringopenapiv3_0.json
docs/openapiv3_0.json
docs/stacopenapiv3_0.json

- Links only added to the OGC doc
- Looks like

Add STAC and DX-Metering API doc links to main OGC API doc

---

pom.xml
src/test/java/ogc/rs/restAssuredTest/TilesMetaDataOnboardingProcessIT.java

This pull request refactors the **TilesMetaDataOnboardingProcessIT** class by replacing the Thread.sleep calls with Awaitility for more dynamic waiting.
Key Changes:
- Utilized Awaitility to improve the reliability and responsiveness of the test by waiting for the job status response instead of using fixed sleep intervals.

Tiles Meta Data Onboarding Process Tests Fix

---

src/test/java/ogc/rs/restAssuredTest/Constant.java
src/test/java/ogc/rs/restAssuredTest/CoveragesIT.java

Added integration tests for Coverages, focusing on validating the authorization flow and ensuring successful retrieval of Coverage JSON links from the database for fetching data from S3.

Integration Tests for coverages

---

src/test/java/ogc/rs/restAssuredTest/CollectionAppendingProcessIT.java
src/test/java/ogc/rs/restAssuredTest/CollectionOnboardingProcessIT.java
src/test/java/ogc/rs/restAssuredTest/TilesMetaDataOnboardingProcessIT.java

- Refactored CollectionAppendingProcessIT and TilesMetaDataOnboardingProcessIT to use Awaitility instead of Thread.sleep() to check for the job status response

Using Awaitility instead of Thread.sleep() in the integration tests to check for the job status

---

src/main/java/ogc/rs/processes/s3PreSignedURLGeneration/Constants.java
src/main/java/ogc/rs/processes/s3PreSignedURLGeneration/S3PreSignedURLGenerationProcess.java

Fix S3 Object Existence Check for Proper 404 Handling
- Modified `checkIfObjectExistsInS3` to complete the promise with `true` only for 404 responses.
- Ensured that other response statuses from S3 result in promise failure with the appropriate error message.

Fix S3 Object Existence Check in S3PreSignedURLGenerationProcess

---

docs/openapiv3_0.json
src/main/java/ogc/rs/apiserver/ApiServerVerticle.java
src/main/java/ogc/rs/apiserver/router/gisentities/ogcprocesses/OgcProcessesEntity.java
src/main/java/ogc/rs/apiserver/util/Constants.java
src/main/java/ogc/rs/jobs/JobsService.java
src/main/java/ogc/rs/jobs/JobsServiceImpl.java

Implemented - https://github.com/orgs/datakaveri/projects/21/views/5?pane=issue&itemId=80687249&issue=datakaveri%7Cogc-resource-server%7C196
-  GET `/jobs`
- Lists all jobs
- Scoped by user to get info on all jobs run by particular user
-  GET `/jobs/<job-ID>/results`
- Get result for a particular job

Implement missing jobs endpoints-  /jobs and /jobs/{jobId}/results

---

src/main/java/ogc/rs/apiserver/ApiServerVerticle.java

- If a STAC asset has a href that is a full URL i.e. an absolute URI, do not create an assets API link (/assets/<asset-id>).
- Instead, send the full URL as the asset href
- This flow is useful for STAC assets that are meant to be public (thumbnails, overviews etc.)

Handle STAC Assets where the href is an absolute URI

---

src/main/resources/db/migration/V17_4__Add_grants_for_existing_STAC_collection_partition_tables.sql

- Grants from the main partition table are not inherited by the partition tables
- Missing grants were causing errors with the `/stac/collections/<collection-id>/items` since the actual collection partition is queried for that
- Added SELECT, DELETE and UPDATE grants for all existing STAC collection partition tables
- INSERT grant was *not* added since inserts should happen through the main partition table to preserve the `p_id` sequence

Bug-Fix: Add select, delete and update GRANTs for existing STAC collection partition tables

---

src/main/java/ogc/rs/processes/ProcessesRunnerImpl.java
src/main/java/ogc/rs/processes/tilesMetaDataOnboarding/TilesMetaDataOnboardingProcess.java
src/main/java/ogc/rs/processes/tilesOnboardingFromExistingFeature/Constants.java
src/main/java/ogc/rs/processes/tilesOnboardingFromExistingFeature/TilesOnboardingFromExistingFeatureProcess.java

This PR introduces the `TilesOnboardingFromExistingFeatureProcess`, which handles the onboarding of tiles from an existing feature collection.
- Added a process flow to validate resource ownership, check feature collection existence, verify tile matrix sets, and onboard tile metadata.
- Integrated ogr2ogr to generate tiles from features and upload them to S3.

Feature: Tiles onboarding from existing features process

---

src/main/java/ogc/rs/apiserver/handlers/StacAssetsAuthZHandler.java
src/test/java/ogc/rs/restAssuredTest/StacAssetsIT.java

The collections_enclosure table uses the field name collections_id, while StacAuthZ was attempting to fetch from collection_id.
This commit updates the logic to first search for collection_id in stac_items_assets and if not found then searches in collections_id (in collections_enclosure) .

bug-fix in StacAuthZ

---

docs/stacopenapiv3_0.json
pom.xml
src/main/java/ogc/rs/apiserver/ApiServerVerticle.java
src/main/java/ogc/rs/apiserver/handlers/StacCollectionOnboardingAuthZHandler.java
src/main/java/ogc/rs/apiserver/router/routerbuilders/EntityRouterBuilder.java
src/main/java/ogc/rs/apiserver/router/routerbuilders/StacRouterBuilder.java
src/main/java/ogc/rs/apiserver/util/Constants.java
src/main/java/ogc/rs/catalogue/CatalogueService.java
src/main/java/ogc/rs/database/DatabaseService.java
src/main/java/ogc/rs/database/DatabaseServiceImpl.java
src/main/java/ogc/rs/database/util/Constants.java
src/main/resources/db/migration/V19__alter_stac_collections_owner.sql
src/test/java/ogc/rs/restAssuredTest/StacCollectionOnboardingIT.java
src/test/resources/integ-db/teardown/deleteStacCollectionOnboarding.sql

The commit includes following changes:-
1. For authorization, STACollectionOnboardingAuthZHandler is created. This validates :  
- The resource should be present in catalogue. 
- The token should be either provider or delegate 
- Token should be OPEN.
- Owner of the resource should be same as sub of token (for provider), did of token (for delegate).
2. In Catalogue Service new method to get item is created as the already existing one uses different filters.
3. The Post STAC Collection API is created. The validation is done through open API spec, followed by authorization. If the item already exists a 409 conflict error is thrown. Then the item is inserted into the tables and partitions are created. If one of the queries fail during transaction the entire onboarding is rolled-back. After …

STAC-Collection Transaction API

---

src/main/java/ogc/rs/apiserver/ApiServerVerticle.java

- PySTAC Client was encountering errors during STAC Item Search since `stac_version` was not being returned

Add `stac_version` to all STAC Items returned in Item Search

---

docs/stacopenapiv3_0.json
src/main/java/ogc/rs/apiserver/ApiServerVerticle.java
src/main/java/ogc/rs/apiserver/handlers/DxTokenAuthenticationHandler.java
src/main/java/ogc/rs/apiserver/handlers/StacItemByIdAuthZHandler.java
src/main/java/ogc/rs/apiserver/router/routerbuilders/EntityRouterBuilder.java
src/main/java/ogc/rs/apiserver/router/routerbuilders/StacRouterBuilder.java
src/main/java/ogc/rs/apiserver/util/AuthInfo.java
src/main/java/ogc/rs/apiserver/util/Constants.java
src/test/java/ogc/rs/restAssuredTest/StacItemByIdIT.java

**Get Pre-Signed URL Support for STAC Assets**
- This PR introduces support for generating AWS S3 GET pre-signed URLs for protected STAC assets in the `/stac/collections/{collectionId}/items/{itemId}` endpoint. This reduces the load on the OGC resource server by allowing direct downloads of large STAC Assets from S3 instead of routing through the server.
- Implemented `StacItemByIdAuthZHandler` – A new handler to validate the token and check collection access from the `ri_details table`.
- _Correct Token_ → Sets `shouldCreate = true` in RoutingContext which can be used to indicate to generate GET pre-signed URLs for all the protected assets.
- _Wrong Token / No Token_ → Sets `shouldCreate = false` in RoutingContext which can be used to indicate to replace href with #, blocking direct …

Get Presigned Url support for STAC assets

---

docs/stacopenapiv3_0.json
src/main/java/ogc/rs/apiserver/ApiServerVerticle.java
src/main/java/ogc/rs/catalogue/CatalogueService.java
src/main/java/ogc/rs/database/DatabaseServiceImpl.java
src/main/resources/db/migration/V19__alter_stac_collections_owner.sql

The PR includes following changes:
- fixed the extent interval to not take null values and throw validation error
- shifted crs to extent according to STAC Transaction request body
- updated the put request body schema foe STAC Collection Transaction to include id only as required field
- fixed the db migration

fix: correct extent handling in request body and db migration

---

docs/stacopenapiv3_0.json
src/main/java/ogc/rs/apiserver/ApiServerVerticle.java
src/main/java/ogc/rs/apiserver/handlers/StacItemOnboardingAuthZHandler.java
src/main/java/ogc/rs/apiserver/router/routerbuilders/EntityRouterBuilder.java
src/main/java/ogc/rs/apiserver/router/routerbuilders/StacRouterBuilder.java
src/main/java/ogc/rs/apiserver/util/Constants.java
src/main/java/ogc/rs/database/DatabaseService.java
src/main/java/ogc/rs/database/DatabaseServiceImpl.java

Added POST API for STAC Items
* Update openAPI spec to have new operationIds for routes for POST API
* Updated Stac router classes
* Updated ApiServerVerticle to allow POST method at /stac/collections/<collection-id>/items route
* Updated DatabaseServiceImpl to insert the data into postgres
Added 409 conflict error handling
* Added 409 conflict handling if one or more STAC item(s) exist already
* Added additional check to verify if the corresponding _collection_ exist for the item to be created

Stac transaction

---

pom.xml
src/main/java/ogc/rs/apiserver/ApiServerVerticle.java
src/main/java/ogc/rs/database/DatabaseServiceImpl.java
src/test/java/ogc/rs/restAssuredTest/StacTransactionIT.java
src/test/resources/integ-db/setup/createStacCollectionForStacTransaction.sql
src/test/resources/integ-db/teardown/deleteStacTransactionData.sql

* Added integration tests with setup and teardown migration scripts
* Includes code fixes
- using `Left join` in `getStacItemById` and `getStacItems` call in DBService to support viewing of Items without Assets
- Changed status code from `201` to `200` for Update Stac Items method.

Added Integration Tests for STAC Transaction APIs

---

example-config/config-example.json
src/main/java/ogc/rs/metering/MeteringServiceImpl.java
src/main/java/ogc/rs/metering/MeteringVerticle.java
src/test/java/ogc/rs/metering/MeteringServiceImplTest.java

**Changes**
- Added separate PgPool for ogc_collections database connection
- Modified `insertIntoPostgresAuditTable` method to use `dbClient` instead of `meteringPgClient`

Bug Fix: Add separate database client for audit table insertions

---

src/main/java/ogc/rs/processes/tilesOnboardingFromExistingFeature/TilesOnboardingFromExistingFeatureProcess.java

- ogr2ogr creates a temporary file during tile creation, this is by default stored in working directory
- in non-writeable filesystems, like in the Docker container, the file cannot be created in the working dir
- hence using the `CPL_TMPDIR` config option set to the temp directory recognized by the JVM so that the file can be created

Update tiles onboarding from existing feat process - set temp directory for ogr2ogr temp file

---

src/main/resources/db/migration/V23_2__Insert_into_crs_to_srid_table.sql
src/main/resources/db/migration/V23_3__insert_core_catalog_create_dynamic_table_and_grant_access.sql

- Created an insertion in crs_to_srid table if the crs 'http://www.opengis.net/def/crs/OGC/1.3/CRS84' doesn't exist. 
- Changed the record core catalog title, description and bbox
- added unique constraint to dynamically created record table

insertion in crs_to_srid

---

Jenkinsfile
pom.xml
src/main/java/ogc/rs/apiserver/ApiServerVerticle.java
src/main/java/ogc/rs/apiserver/handlers/TokenLimitsEnforcementHandler.java
src/main/java/ogc/rs/apiserver/router/gisentities/ogcfeatures/OgcFeaturesEntity.java
src/main/java/ogc/rs/apiserver/router/routerbuilders/EntityRouterBuilder.java
src/main/java/ogc/rs/apiserver/util/Constants.java
src/main/java/ogc/rs/apiserver/util/Limits.java
src/main/java/ogc/rs/common/Constants.java
src/main/java/ogc/rs/database/DatabaseService.java
src/main/java/ogc/rs/database/DatabaseServiceImpl.java
src/main/java/ogc/rs/database/util/FeatureQueryBuilder.java
src/test/java/ogc/rs/restAssuredTest/TokenLimitsEnforcementHandlerIT.java

This PR introduces support for enforcing spatial access limits based on token-defined constraints: bboxLimit (via the bbox query parameter) and featLimit (via feature-level access). When present in the token, these constraints restrict users from accessing geometries beyond the specified spatial extent.
- The sample token:
```
{
"sub": "fd47486b-3497-4248-ac1e-082e4d37a66c",
"iss": "fakeauth.ugix.io",
"aud": "ogc.server.test.com",
"exp": 1724278224,
"iat": 1724235024,
"iid": "ri:83c2e5c2-3574-4e11-9530-2b1fbdfce832",
"role": "consumer",
"cons": {
"access": ["api", "sub", "file", "async"],
"limits": {
"bbox": [-123.0, 37.0, -122.0, 38.0],
"feat": {
"39b9d0f5-38be-4603-b2db-7b678d9c3870": [
"1", "2", "3", "4", "5", "6", "7", "8", "9", "10"
]
},
"dataUsage": "100:gb",
"apiHits": 100, 
"iat": …
```

Enforce bbox and feature limits using token-based constraints

---

src/main/java/ogc/rs/apiserver/ApiServerVerticle.java
src/main/java/ogc/rs/database/DatabaseServiceImpl.java
src/main/java/ogc/rs/database/util/MulticornErrorHandler.java

- Added new class `MulticornErrorHandler` to check for Multicorn script errors and convert them to OgcExceptions
- Used above class in `onFailure` blocks of `getFeatures` and `getFeature` methods in `DatabaseServiceImpl` (OGC Feature API DB methods).
- Simplified `onFailure` blocks for OGC Feature API methods in `ApiServerVerticle` to fail the RoutingContext and allow the `FailureHandler` to take care of it

Handle Multicorn script errors for the OGC Features APIs

---

src/main/java/ogc/rs/database/DatabaseServiceImpl.java
src/main/java/ogc/rs/database/util/FeatureQueryBuilder.java

* Updated the _FeatureQueryBuilder_ class to handle multiple attribute in the query.
* Although not explicitly mentioned in the Features Part-I standard, previously, the parameter in the Feature _properties_ only allowed single attribute query.
* Now the update supports querying multiple parameters in the _properties_ object.

Features multi attribute query
